// Mocks generated by Mockito 5.4.5 from annotations
// in basic_notes/test/service/note_list_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:basic_notes/model/note_list.dart' as _i2;
import 'package:basic_notes/repository/file/file_note_list_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNoteList_0 extends _i1.SmartFake implements _i2.NoteList {
  _FakeNoteList_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FileNoteListRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFileNoteListRepository extends _i1.Mock
    implements _i3.FileNoteListRepository {
  MockFileNoteListRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> save(_i2.NoteList? noteList) =>
      (super.noSuchMethod(
            Invocation.method(#save, [noteList]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.NoteList> load() =>
      (super.noSuchMethod(
            Invocation.method(#load, []),
            returnValue: _i4.Future<_i2.NoteList>.value(
              _FakeNoteList_0(this, Invocation.method(#load, [])),
            ),
          )
          as _i4.Future<_i2.NoteList>);
}
